### PR TITLE
Re-render v1.0.2 on linux_aarch64, linux_ppc64le, and osx_arm64

### PR DESCRIPTION
**Pull request by neutrinoceros**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [N/A] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
@conda-forge-admin, please rerender

**Comment by yut23** [comment]
The Linux failures should be fixable by something like `crossc-openmp.patch` in the yt feedstock

**Comment by yut23** [comment]
osx_arm64 probably needs `cross-python` in the build environment

**Comment by neutrinoceros** [comment]
thanks a lot for your help @yut23, you saved me a lot of time figuring this stuff up, I really appreciate it !

**Pull request merged**
